name: Publish docs to Wiki

on:
  push:
    branches:
      - main # This can be changed to any branch of your preference

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

env:
  USER_TOKEN: ${{ secrets.GH_WIKI_PAT }} # This is the repository secret personal access token
  USER_NAME: OrcaSlicerBot # Enter the username of your (bot) account
  OWNER: OrcaSlicer # Target repository owner
  REPOSITORY_NAME: OrcaSlicer # Target repository name

jobs:
  publish_docs_to_wiki:
    name: Updated OrcaSlicer Wiki
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: debug info
        run: |
          cat ./Home.md

      # Publish content to wiki
      - name: Pull content from wiki
        working-directory: ${{ github.workspace }}/..
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_NAME"@users.noreply.github.com
          git clone https://"$USER_TOKEN"@github.com/"$OWNER"/"$REPOSITORY_NAME".wiki.git tmp_wiki
          echo "---debug info before rsync---"
          cat ./tmp_wiki/Home.md
          echo "---github workspace---"
          echo ${{ github.workspace }}
          rsync -av --delete ${{ github.workspace }} tmp_wiki/ --exclude .git
          cd tmp_wiki
          echo "---debug info after rsync---"
          cat ./Home.md
          git add .
          git commit -m "Updated Wiki content" 
          git push origin master
